### ISSUE TITLE
Call to undefined function mime_content_type()

### ISSUE THREAD

**Issue by jagc** [ZDroid/hackwork#2]
# Description
Running [hackwork] out of the box. After configuring [core/hackwork.php] to run on my environment (see fig.1). I get this error(see fig.2):

**"Fatal error: Call to undefined function mime_content_type() in D:\Programs\Ampps\www\hackwork\layouts\default\i.functions.php on line 37"**

# Screenshots
![hackwork-config](https://cloud.githubusercontent.com/assets/467134/5658515/026f8bd8-973e-11e4-8148-7e12c57eed41.PNG)
fig.1

![hackwork-error](https://cloud.githubusercontent.com/assets/467134/5658516/0cf42f64-973e-11e4-9291-647a69a35733.PNG)
fig.2

# Environment
AMPPS 2.8
Apache 2.2
PHP 5.4
Windows 7 Ultimate 64bit

**Comment by ZDroid** [comment]
I made mistake in first commit, it should be okay now.

**Comment by cybernet** [comment]
for starters you should use linux

**Comment by jagc** [comment]
@cybernet I only use linux for live production environment.

@ZDroid Hey, Thanks! I came across an error when i ran the framework again:

    "Fatal error: Class 'finfo' not found in D:\Programs\Ampps\www\hackwork\layouts\default\i.functions.php on line 11"

I found out that the [**php_fileinfo**] extension was disabled at [**php.ini**] by default. I enabled it and now it works. Just sharing for others who might come across the same problem.
Or maybe you could apply some modifications - to add an exception to indicate the need to install {**php_fileinfo.dll**} (windows) | {**fileinfo.so**} (linux).

**Comment by erm3nda** [comment]
@jagc Developing under a platform that is not the target platform? Can't believe you're serious.
You will get/face problems that you will not have on the production env, and viceversa, once you install them you will got new problems. I don't say that's bad, for sure you'll learn cross platform PHP things, but is nothing practical for real life, and do not talk for production.

:D

**Comment by erm3nda** [comment]
Can u guys share something built with that? i'll glad to see.

**Comment by zdroid** [comment]
Sorry for being late with publishing this. It's shipped in v2.0.2 release now. :shipit:

**Comment by jagc** [comment]
Thanks @zdroid.

@erm3nda Thing is, It's very easy to say "use linux" like what @cybernet said as a quick and easy solution once someone from the dev forums declares that s/he's using windows as a dev env. For me, those words don't look like tackling the solution, it looks like you're avoiding it. So if a guy can't provide any useful solution in the first place, just tell him that you are actually using the env they suggested.

If you're talking about practicality. There are tons, you just don't know because you haven't come across the cases where it is "practical" yet. Why not talk "for production" if it is actually "**For Production**".

**Comment by PhanDung1503** [comment]
@jagc thanks you very much! your comment help me to solved my problem

**Comment by erm3nda** [comment]
@jagc I must admit that you're right.
